routes/web.php
		<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['web']], function () {
	Route::get('blog/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');
	Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);
	Route::get('contact','PagesController@getContact');
	Route::get('about', 'PagesController@getAbout');
	Route::post('contact', 'PagesController@postContact');
	Route::get('/', 'PagesController@getIndex');
	Route::resource('posts', 'PostController');
		Route::resource('tags','TagsController',['except' => ['create']]);

		//comments
		Route::post('comments/{post_id}',['uses' =>'CommentsController@store', 'as' => 'comments.store']);
	//categories
	Route::resource('categories','CategoryController',['except' => ['create']]);
	Route::post('/search-posts','PostController@search')->name('search.posts');
	
});
Route::get('pdf','PdfController@index');
Route::get('parliament-videos-pdf','PdfController@videos');
Route::get('csv','PagesController@getCsv');
Route::get('pay','PayOrderController@store');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::view('users','users');


// livewire routes from here
// Route::get('livewire','HomeController@livewire');
// Route::view('livewire/contacts','cms-livewire.contact');

Route::livewire('/livewire', 'home')->middleware('auth');
Route::group(['middleware' => 'guest'], function(){
	Route::livewire('/livewire/login', 'login')->name('livewire-login');
	Route::livewire('/livewire/register', 'register');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Post;
class Tag extends Model
{
     public function posts()
    {
    	return $this->belongsToMany('App\Post');
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;
use Session;

class TagsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();
        return view('tags.index')->withTags($tags);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,['name' => 'required|max:255']);
        $tag = new Tag;
        $tag->name = $request->name;
        $tag->save();

        Session::flash('success','New Tag Was Successfully Created');
        return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tags =Tag::find($id);
        return view('tags.show')->withTag($tags);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tags = Tag::find($id);
        return view('tags.edit')->withTag($tags);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tag = Tag::find($id);

        $this->validate($request, ['name' => 'required|max:255']);

        $tag->name = $request->name;
        $tag->save();

        Session::flash('success','Tag Updated Successfully');
        
        return redirect()->route('tags.show',$tag->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tag =Tag::find($id);
        $tag->posts()->detach();
                
        $tag->delete();

        Session::flash('success','Tag has been deleted sucessfully');
        return redirect()->route('tags.index');
    }
}

resources/views/tags/edit.blade.php
@extends('layouts.main')

@section('title','| Edit Tag')


@section('content')

	{{ Form::model($tag, ['route' => ['tags.update',$tag->id],'method' =>'PUT'])}}
		{{ Form::label('name','Title')}}
		{{Form::text('name',null,['class' => 'form-control']) }}
		{{Form::submit('Save Changes', ['class' => 'btn btn-success' ,'style' => 'margin-top : 20px;']) }}
	{{ Form::close()}}

@endsection

resources/views/tags/index.blade.php
@extends('layouts.main')

@section('title',' | Alll Tags')

@section('content')
<br>
	<div class="row">
		<div class="col-md-8">
			<h3>Tags</h3>
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
					</tr>
				</thead>
				
				<tbody>
					@foreach($tags as $tag)
					<tr>
						<td>{{ $tag -> id}}</td>
						<td><a href="{{ route('tags.show',$tag->id)}}">{{ $tag -> name}}</a></td>
					</tr>
					@endforeach
				</tbody>

			</table>
		</div>

		<div class="col-md-4">
			<div class="card">
				<div class="card-body" style="background-color: #e0e0e0;">
					{!! Form::open(['route' => 'tags.store', 'method' => 'POST']) !!}
				
						<h4>New Tag</h4>
						{{ Form::label('name','Name') }}
						{{ Form::text('name',null,['class' => 'form-control']) }}
						<br>
						{{ Form::submit('Create New Tag', ['class' => 'btn btn-primary btn-block'])}}	
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
	
@endsection

resources/views/tags/show.blade.php
@extends('layouts.main')

@section('title',"| $tag->name Tag")

@section('content')
	<br>
	<div class="row">
		<div class="col-md-8">	
			<h4>{{ $tag->name}} Tag <small style="font-size : 13px; color:gray;">{{$tag->posts()->count() }}Posts</small></h4>
		</div>
		
		<div class="col-md-4">
			<div class="col-md-12 offset-md-8">
				{{ Form::open(['route' => ['tags.destroy', $tag->id], 'method' => 'DELETE']) }}
					{{ Form::submit('Delete',['class' => 'btn btn-danger btn-sm'])}}
				{{ Form::close()}}
				<a href="{{ route('tags.edit',$tag->id)}}" class="btn btn-primary btn-sm" style="margin-top: -60px; margin-left: -50px;">Edit</a>
				
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<table class="table">
				<thead>	
					<tr>
						<th>#</th>
						<th>Title</th>
						<th>Tags</th>
						<th>Action</th>
					</tr>
				</thead>

				<tbody>
					@foreach($tag->posts as $post)
					<tr>
						<td>{{ $post->id}} </td>
						<td>{{ $post->title}}</td>
						<td>@foreach($post->tags as $tag)
							<span class="badge badge-warning">{{ $tag->name}}</span>
						@endforeach
						</td>
						<td> <a href="{{route('posts.show',$post->id)}}" class="btn btn-primary btn-sm">View</a> </td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>	

@endsection