routes/web.php
		<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['web']], function () {
	Route::get('blog/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');
	Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);
	Route::get('contact','PagesController@getContact');
	Route::get('about', 'PagesController@getAbout');
	Route::post('contact', 'PagesController@postContact');
	Route::get('/', 'PagesController@getIndex');
	Route::resource('posts', 'PostController');
		Route::resource('tags','TagsController',['except' => ['create']]);

		//comments
		Route::post('comments/{post_id}',['uses' =>'CommentsController@store', 'as' => 'comments.store']);
	//categories
	Route::resource('categories','CategoryController',['except' => ['create']]);
	Route::post('/search-posts','PostController@search')->name('search.posts');
	
});
Route::get('pdf','PdfController@index');
Route::get('parliament-videos-pdf','PdfController@videos');
Route::get('csv','PagesController@getCsv');
Route::get('pay','PayOrderController@store');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::view('users','users');


// livewire routes from here
// Route::get('livewire','HomeController@livewire');
// Route::view('livewire/contacts','cms-livewire.contact');

Route::livewire('/livewire', 'home')->middleware('auth');
Route::group(['middleware' => 'guest'], function(){
	Route::livewire('/livewire/login', 'login')->name('livewire-login');
	Route::livewire('/livewire/register', 'register');
});

resources/views/partials/_footer.blade.php
	<hr>
    <p class="text-center">&copy Copyright Basanta - All Rights Reserved 2019</p>
    

resources/views/partials/_head.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Laravel Blog @yield('title')</title>
  </head>

resources/views/partials/_messages.blade.php
@if (Session::has('success'))
	<div class="alert alert-success" role="alert">
		<strong>Success: </strong> {{ Session::get('success')}}
	</div>
@endif

@if(count($errors) > 0)
	<div class="alert alert-danger" role="alert">
		<strong>Errors: </strong> 
		@foreach($errors->all() as $error)
			<ul>
				<li>{{$error}}</li>
			</ul>
		@endforeach
	</div>
@endif

resources/views/partials/_nav.blade.php
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Laravel Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="{{ Request::is('/') ? "active" :"" }}">
                <a class="nav-link" href="/">Home </a>
            </li>

            <li class="{{ Request::is('blog') ? "active" :"" }}">
                <a class="nav-link" href="/blog">Blog</a>
            </li>

            <li class="{{ Request::is('about') ? "active" :"" }}">
                <a class="nav-link" href="/about">About</a>
            </li>

            <li class="{{ Request::is('contact') ? "active" :"" }}">
                <a class="nav-link" href="/contact">Contact</a>
            </li>

            
        </ul>

        <ul class="navbar-nav ml-auto">
           <!-- Authentication Links -->
            @guest
            <li class="nav-item">
               <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
            </li>
            @if (Route::has('register'))
            <li class="nav-item">
                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
            </li>
            @endif
            @else
              <li class="nav-item dropdown ">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               {{ Auth::user()->name}}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{{route('posts.index')}}">Posts</a>
                <a class="dropdown-item" href="{{route('categories.index')}}">Categories</a>
                <a class="dropdown-item" href="{{route('tags.index')}}">Tags</a>
              </div>
            </li>

           <li class="nav-item">
              <a class="nav-link" href="{{ route('logout') }}"
                 onclick="event.preventDefault();
                 document.getElementById('logout-form').submit();">
                 {{ __('Logout') }}
              </a>

              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  @csrf
              </form>
           </li>
               @endguest
            </ul>
      </div>  
  </nav>